#!/bin/bash
echo "compiling KitchNMain console application..."
g++ -std=c++11 KitchNMain.cpp Recipe.cpp Ingredient.cpp Notification.cpp RecipeIngredient.cpp ShoppingList.cpp SampleData.cpp -o run 
echo "done -> ./run to execute"