#include "Includes.h"
#include <string>

using namespace std;

void KitchNMain::loadSampleData() {


  // Ingredients
  ingredients.emplace_back("Bread", 2);
  ingredients.emplace_back("Cereal", 5);
  ingredients.emplace_back("Carrot", 10);
  ingredients.emplace_back("Chicken Breast", 4);
  ingredients.emplace_back("Tortillas", 50);
  ingredients.emplace_back("Beer", 100);
  ingredients.emplace_back("Tuna", 8);
  
  // Shopping List
  shoppingList.addItem("Milk");
  shoppingList.addItem("Peanut Butter");
  shoppingList.addItem("Pasta");
  shoppingList.addItem("Apple");
  shoppingList.addItem("Steak");
  shoppingList.addItem("Juice");
  shoppingList.addItem("Ketchup");
  shoppingList.addItem("Celery");
  shoppingList.addItem("Lettuce");

  // Recipes
  string title;
  int prepTime;
  int cookTime;
  string cuisineType;
  vector<RecipeIngredient> myIngredients;
  vector<string> mySteps;


  title = "Poppy Seed Chicken Salad";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Salad";
  myIngredients.emplace_back("2 cups", "Chicken Salad");
  myIngredients.emplace_back("1/4 cup", "Poppy Seed Salad Dressing");
  myIngredients.emplace_back("1/2 cup - roasted","Pecans");
  myIngredients.emplace_back("1/2 cup - halved","Grapes");
  myIngredients.emplace_back("1 package","pita chips");
  mySteps.push_back("Combine first 4 ingredients in a bowl.");
  mySteps.push_back("Cover and chill until ready to serve.");
  mySteps.push_back("Serve with crackers or pita chips.");
  Recipe* rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();

  title = "Reuben Sandwich";
  prepTime = 15;
  cookTime = 10;
  cuisineType = "Sandwich";
  myIngredients.emplace_back("8 slices", "rye bread");
  myIngredients.emplace_back("3/4 cup", "thousand island dressing");
  myIngredients.emplace_back("1 (16 ounce) can - drained", "sauerkraut");
  myIngredients.emplace_back("8 slices", "swiss cheese");
  myIngredients.emplace_back("8 slices", "pastrami");
  myIngredients.emplace_back("1/4 cup - softened", "margarine");
  mySteps.push_back("Spread each slice of bread with thousand island dressing.");
  mySteps.push_back("Top 4 of the bread slices with sauerkraut, cheese, and pastrami.");
  mySteps.push_back("Place remaining bread slices on sandwich and spread margarine on outsides of sandwich.");
  mySteps.push_back("Heat skillet over medium high heat.");
  mySteps.push_back("Grill until browned, then turn and grill until heated though and cheese is melted.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();

  title = "Rockin' Taco Salad";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Salad";
  myIngredients.emplace_back("2/3 cup", "low-fat veggie chili");
  myIngredients.emplace_back("3 cups - chopped", "romaine lettuce");
  myIngredients.emplace_back("1/4 cup - chopped", "tomato");
  myIngredients.emplace_back("1/4 cup - shredded", "fat-free Cheddar cheese");
  myIngredients.emplace_back("1 tbsp - chopped or sliced", "black olives");
  myIngredients.emplace_back("2 tbsps", "fat-free sour cream");
  myIngredients.emplace_back("6 - crushed", "tortilla chips");
  mySteps.push_back("Prepare chili as directed on package. Set aside.");
  mySteps.push_back("Place lettuce in a big bowl and top with tomatoes, chili and cheese.");
  mySteps.push_back("Add the olives and sour cream.");
  mySteps.push_back("Finish off with the crushed tortilla chips, and enjoy!");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Mango Chutney Turkey Wrap";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Wrap";
  myIngredients.emplace_back("1 (8-inch)", "whole wheat tortilla");
  myIngredients.emplace_back("1/4 tsp", "mango chutney");
  myIngredients.emplace_back("1/4 tsp", "Mediterranean spice blend");
  myIngredients.emplace_back("4 slices - oven roasted", "turkey");
  myIngredients.emplace_back("1/4 cup", "baby spinach");
  myIngredients.emplace_back("1 slice", "fat-free feta cheese");
  mySteps.push_back("Spread the mango chutney over the tortilla and sprinkle with the Mediterranean spice blend.");
  mySteps.push_back("Top with turkey, spinach and cheese.");
  mySteps.push_back("Roll-up and serve immediately or wrap in plastic wrap and refrigerate until ready to serve.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Steak Fajita Wraps";
  prepTime = 10;
  cookTime = 1;
  cuisineType = "Fajita";
  myIngredients.emplace_back("4", "whole wheat tortilla");
  myIngredients.emplace_back("12 ounce - cooked - sliced", "flank steak");
  myIngredients.emplace_back("1 cup", "salsa");
  myIngredients.emplace_back("1 cup -sliced", "avocado");
  myIngredients.emplace_back("1/2 cup - shredded", "cheddar cheese");
  myIngredients.emplace_back("4 medium", "apple");
  mySteps.push_back("Heat the tortillas in the microwave until soft - about 10 seconds.");
  mySteps.push_back("Top each tortilla with 3 ounces sliced flank steak, 1/4 cup salsa, sliced avocado, and 2 tbsp of cheese.");
  mySteps.push_back("Wrap the tortilla around the fillings.");
  mySteps.push_back("Heat in a nonstick skillet, toaster oven, or microwave, or serve cold.");
  mySteps.push_back("Serve with apples or pears.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Watercress Salad";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Salad";
  myIngredients.emplace_back("2 tbsp", "red wine vinegar");
  myIngredients.emplace_back("3 tbsp", "extra-virgin olive oil");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("2 bunches - hand torn", "watercress");
  myIngredients.emplace_back("1 cup - toasted", "almonds");
  myIngredients.emplace_back("1/4 cup - dried", "cranberries");
  mySteps.push_back("Make a quick vinaigrette by whisking together the vineger oil, salt and pepper.");
  mySteps.push_back("Pour the vinaigrette over the watercress and toss to coat.");
  mySteps.push_back("Garnish with the toasted slivered almonds and dried cranberries.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Tuscan Panino with Soppressata and Marinated Artichokes";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Sandwich";
  myIngredients.emplace_back("6 slices", "Pugliese bread");
  myIngredients.emplace_back("drizzle", "extra-virgin olive oil");
  myIngredients.emplace_back("to taste", "sea salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("9 slices", "soppressata");
  myIngredients.emplace_back("9 slices", "pecorino cheese");
  myIngredients.emplace_back("3 - thinly sliced - marinated", "artichoke");
  mySteps.push_back("Lay out 6 slices of bread on a cutting board.");
  mySteps.push_back("Drizzle with olive oil and season with sea salt and black pepper.");
  mySteps.push_back("Top 3 slices of bread each with 3 slices of soppressata, 3 slices of cheese and divide the marinated artichokes evenly amoung the sandwiches.");
  mySteps.push_back("Top with the remaining 3 pieces of bread.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Edamame Salad";
  prepTime = 10;
  cookTime = 0;
  cuisineType = "";
  myIngredients.emplace_back("2 cups", "edamame");
  myIngredients.emplace_back("2 tbsp", "olive oil");
  myIngredients.emplace_back("whole - zest", "lemon");
  myIngredients.emplace_back("half - juice", "lemon");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("to taste - shaved", "pecorino cheese");
  myIngredients.emplace_back("to taste - chopped", "mint");
  mySteps.push_back("Part boil edamame and drain.");
  mySteps.push_back("In a bowl, whisk together olive oil, lemon zest, lemon juice, salt and pepper.");
  mySteps.push_back("Add edamame to bowl and mix.");
  mySteps.push_back("To serve, add shaved pecorino cheese and roughly chopped mint.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Nutella Mug Cake";
  prepTime = 2;
  cookTime = 2;
  cuisineType = "Mug Cake";
  myIngredients.emplace_back("4 tbsp", "self-rising flour");
  myIngredients.emplace_back("3 tbsp", "cocoa powder");
  myIngredients.emplace_back("3 tbsp", "nutella");
  myIngredients.emplace_back("3 tbsp", "milk");
  myIngredients.emplace_back("1 tbsp", "sugar");
  myIngredients.emplace_back("1 tbsp", "olive oil");
  myIngredients.emplace_back("1", "egg");
  mySteps.push_back("Combine all ingredients in an oversized microwave safe mug.");
  mySteps.push_back("Whisk lightly with a fork until combined and smooth.");
  mySteps.push_back("Microwave for a minute, watching as the cake rises in the mug, stopping if it is about to overflow.");
  mySteps.push_back("Continue a couple of times for 10 second intervals until cooked.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Oreo Popcorn";
  prepTime = 5;
  cookTime = 3;
  cuisineType = "Popcorn";
  myIngredients.emplace_back("12", "oreo cookie");
  myIngredients.emplace_back("11 ounces", "white chocolate chips");
  myIngredients.emplace_back("5 cups - popped", "popcorn");
  mySteps.push_back("Place Oreos in food processor and pulse several times to finely chop (do not reduce them to dust).");
  mySteps.push_back("Melt chocolate by heating in microwave for 30 seconds then stirring and repeating until smooth and melted.");
  mySteps.push_back("Put popcorn in a large bowl.");
  mySteps.push_back("Pour chocolate over popcorn and mix to coat evenly.");
  mySteps.push_back("Sprinkle cookie pieces over popcorn and mix to coat evenly.");
  mySteps.push_back("Allow to cool and serve.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "3-Minute Fudge";
  prepTime = 5;
  cookTime = 3;
  cuisineType = "Fudge";
  myIngredients.emplace_back("1 cup", "sweetened condensed milk");
  myIngredients.emplace_back("1 (12 ounce) bag", "semisweet chocolate chips");
  myIngredients.emplace_back("1 (1 ounce) square - chopped", "semisweet baking chocolate");
  mySteps.push_back("Grease an 8x8-inch square baking dish with butter.");
  mySteps.push_back("Place sweetened condensed milk, chocolate chips, and baking chocolate in a microwave-safe dish.");
  mySteps.push_back("Cook in microwave on low power until chocolate has melted - about 3 minutes.");
  mySteps.push_back("Beat with an electric mixer until smooth - about 1 minute.");
  mySteps.push_back("Pour fudge into the prepared baking dish.");
  mySteps.push_back("Let stand until set - 3 to 4 hours.");
  mySteps.push_back("Cut into squares to serve.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Turkey Sandwich with Provolone and Pickled Vegetables";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Sandwich";
  myIngredients.emplace_back("1 - split", "ciabatta roll");
  myIngredients.emplace_back("1 tsp", "olive oil");
  myIngredients.emplace_back("3 ounces - thinly sliced - roasted", "turkey");
  myIngredients.emplace_back("1/3 cup - drained and chopped", "giardiniera");
  myIngredients.emplace_back("2 slices", "provolone");
  mySteps.push_back("Drizzle the ciabatta with the oil.");
  mySteps.push_back("Form a sandwich with the turkey, giardiniera, and provolone.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Pesto";
  prepTime = 5;
  cookTime = 0;
  cuisineType = "Pesto";
  myIngredients.emplace_back("3 tbsp", "extra-virgin olive oil");
  myIngredients.emplace_back("4 cups", "basil");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  mySteps.push_back("Put basil and olive oil in food processor.");
  mySteps.push_back("Add salt and pepper to taste.");
  mySteps.push_back("Blend until creamy.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Shells and White Cheddar";
  prepTime = 5;
  cookTime = 20;
  cuisineType = "Mac and Cheese";
  myIngredients.emplace_back("2 cups", "milk");
  myIngredients.emplace_back("2 cups", "shells");
  myIngredients.emplace_back("1 cup", "white cheddar cheese");
  mySteps.push_back("In medium saucepan, bring the milk and pasta to a simmer over medium heat.");
  mySteps.push_back("Cook for about 20 minutes, stirring often and making sure the milk doesn't boil.");
  mySteps.push_back("Once the pasta is al dente, remove from heat and add the cheese.");
  mySteps.push_back("Stil until melted.");
  mySteps.push_back("If you like it creamier, add more milk.");
  mySteps.push_back("Salt to taste.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Microwave Egg, Canadian Bacon, and Cheese Muffin";
  prepTime = 1;
  cookTime = 1;
  cuisineType = "Biscuit";
  myIngredients.emplace_back("1 slice", "canadian bacon");
  myIngredients.emplace_back("1 - beaten", "egg");
  myIngredients.emplace_back("1 tbsp - shredded", "cheddar cheese");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("1 - split -toasted", "wheat muffin");
  mySteps.push_back("Line the bottom of 8-oz microwave-safe ramekin or custard cup with Canadian bacon.");
  mySteps.push_back("Pour egg over bacon.");
  mySteps.push_back("Microwave on HIGH 30 seconds; stir.");
  mySteps.push_back("Microwave until egg is almost set - 15 to 30 more seconds.");
  mySteps.push_back("Season with salt and pepper.");
  mySteps.push_back("Top with cheese.");
  mySteps.push_back("Serve immediately on English muffin.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Microwave Veggie Nut Coffee Cup Scramble";
  prepTime = 4;
  cookTime = 1;
  cuisineType = "Eggs";
  myIngredients.emplace_back("1", "egg");
  myIngredients.emplace_back("1 tbsp", "water");
  myIngredients.emplace_back("1/4 cup - chopped", "broccoli");
  myIngredients.emplace_back("1/4 cup - chopped", "mushrooms");
  myIngredients.emplace_back("1 tbsp - shredded", "mozzarella");
  myIngredients.emplace_back("1 tbsp - chopped - toasted", "walnuts");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  mySteps.push_back("Coat 12-oz microwave-safe coffe mug with cooking spray.");
  mySteps.push_back("Add egg, water, brocolli and mushrooms.");
  mySteps.push_back("Beat until blended.");
  mySteps.push_back("Microwave on HIGH 30 seconds; stir.");
  mySteps.push_back("Microwave until egg is almost set - 30 to 45 more seconds.");
  mySteps.push_back("Season with salt and pepper.");
  mySteps.push_back("Top with cheese and walnuts.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Saint Nick's Egg Nog";
  prepTime = 10;
  cookTime = 15;
  cuisineType = "Eggnog";
  myIngredients.emplace_back("6 - large", "egg");
  myIngredients.emplace_back("1/4 cup", "sugar");
  myIngredients.emplace_back("1/4 tsp", "salt");
  myIngredients.emplace_back("4 cups", "milk");
  myIngredients.emplace_back("1 tsp", "vanilla");
  myIngredients.emplace_back("12", "cinnamon stick");
  mySteps.push_back("Beat eggs, sugar and salt in large heavy saucepan until blended.");
  mySteps.push_back("Stir in 2 cups milk.");
  mySteps.push_back("Cook over low heat, stirring constantly but gently, until mixture is just thick enough to just coat a metal spoon with a thin film and temperature reaches about 160 F - about 15 minutes.");
  mySteps.push_back("Do not allow to boil. Remove from heat immediately.");
  mySteps.push_back("Stir in remaining 2 cups milk and vanilla.");
  mySteps.push_back("Refrigerate, covered, until thoroughly chilled - several hours or overnight.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Pasta Skillet Dinner";
  prepTime = 30;
  cookTime = 0;
  cuisineType = "Pasta";
  myIngredients.emplace_back("2 cups (7 oz) - uncooked", "zita pasta");
  myIngredients.emplace_back("1 lb - lean", "ground beef");
  myIngredients.emplace_back("1 jar (14 oz)", "tomato pasta sauce");
  myIngredients.emplace_back("1/2 cup", "water");
  myIngredients.emplace_back("1/2 cup", "sour cream");
  myIngredients.emplace_back("1 cup - shredded", "cheddar cheese");
  mySteps.push_back("Cook pasta as directed on package; drain. Cover to keep warm.");
  mySteps.push_back("Meanwhile, in 10-inch skillet, cook ground beef over medium-high heat, stirring frequently, until thoroughly cooked; drain.");
  mySteps.push_back("Stir in pasta sauce and water.");
  mySteps.push_back("Reduce heat to medium; simmer uncovered for 5 minutes.");
  mySteps.push_back("Stir in cooked pasta. In small bowl, mix cream and cheese.");
  mySteps.push_back("Spoon over pasta mixture.");
  mySteps.push_back("Reduce heat to low; cover and cook 6 to 8 minutes or until thoroughly heated.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "One-Pot French Onion Soup Rice Skillet";
  prepTime = 5;
  cookTime = 20;
  cuisineType = "Rice";
  myIngredients.emplace_back("1 lb", "ground beef");
  myIngredients.emplace_back("1 - small - yellow", "onion");
  myIngredients.emplace_back("1 cup - uncooked", "long-grain white rice");
  myIngredients.emplace_back("2 1/2 cups", "beef flavored broth");
  myIngredients.emplace_back("1 package", "onion soup mix");
  myIngredients.emplace_back("1/2 cup - grated", "Gruyere cheese");
  mySteps.push_back("Heat 12-inch skillet over medium heat; add beef and onion.");
  mySteps.push_back("Cook until beef is no longer pink, crumbling beef as it cooks; drain.");
  mySteps.push_back("Stir in rice, broth, and onion soup mix.");
  mySteps.push_back("Heat to boiling, reduce heat to simmering.");
  mySteps.push_back("Cover and cook about 15 minutes, stirring halfway through, until rice is tender.");
  mySteps.push_back("Remove from heat; stir in cheese.");
  mySteps.push_back("Cover; let stand about 2 minutes or until melted.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Easy Beef Burrito Skillet";
  prepTime = 20;
  cookTime = 5;
  cuisineType = "Burrito";
  myIngredients.emplace_back("1 lb", "ground beef");
  myIngredients.emplace_back("1 package (1 oz)", "taco seasoning mix");
  myIngredients.emplace_back("1 cup", "water");
  myIngredients.emplace_back("1 cup", "chunky salsa");
  myIngredients.emplace_back("1 can - rinsed and drained", "black beans");
  myIngredients.emplace_back("4 - sliced into 1-inch strips", "floar tortilla");
  myIngredients.emplace_back("1 cup - shredded", "mexican blend cheese");
  myIngredients.emplace_back("1/2 cup", "sour cream");
  myIngredients.emplace_back("1/4 cup - sliced", "green onion");
  mySteps.push_back("In a large skillet, brown beef until no longer pink; drain.");
  mySteps.push_back("Add taco seasoning, water, salsa and beans.");
  mySteps.push_back("Cook over medium heat for 3-5 minutes or until sauce thickens.");
  mySteps.push_back("Reduce heat to low.");
  mySteps.push_back("Stir in the tortilla strips and then top with cheese.");
  mySteps.push_back("Remove skillet from heat and let cheese melt.");
  mySteps.push_back("Top with sour cream and sprinkle with green onions.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Potato-Crusted Pizza";
  prepTime = 10;
  cookTime = 35;
  cuisineType = "Pizza";
  myIngredients.emplace_back("1 tbsp", "olive oil");
  myIngredients.emplace_back("1 package (30-oz) - frozen", "shredded potato rounds");
  myIngredients.emplace_back("1 (1-oz) package - torn - fresh", "basil");
  myIngredients.emplace_back("1 (28-oz) package - drained -diced", "tomatoes");
  myIngredients.emplace_back("2 cups - shredded", "pizza cheese blend");
  mySteps.push_back("Preheat oven to 450.");
  mySteps.push_back("Brush a 15 1/2 x 10 1/2 inch jelly roll pan with oil and arrange potatoes in a single layer in pan.");
  mySteps.push_back("Bake 10 minutes.");
  mySteps.push_back("Flatten potatoes using the back of a wooden spoon until rounds touch and cover entire pan.");
  mySteps.push_back("Bake 20 more minutes or until crisp.");
  mySteps.push_back("Top with remaining ingredients.");
  mySteps.push_back("Bake 5 to 10 more minutes or until cheese melts.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Grapefruit and Smoked Trout Cobb Salad";
  prepTime = 20;
  cookTime = 15;
  cuisineType = "Salad";
  myIngredients.emplace_back("1 - halved - thinly sliced", "grapefruit");
  myIngredients.emplace_back("2 tsp", "Dijon mustard");
  myIngredients.emplace_back("1/4 cup", "extra-virgin olive oil");
  myIngredients.emplace_back("2 cups - tough stems removed", "watercress");
  myIngredients.emplace_back("8 ounce - flaked -smoked", "trout");
  myIngredients.emplace_back("1 - minced", "shallot");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("3 cups - chopped", "romaine lettuce");
  myIngredients.emplace_back("3 cups -cooked", "farro");
  myIngredients.emplace_back("1 - pitted, peeled, sliced", "avocado");
  mySteps.push_back("For the dressing, whisk together grapefruit juice, shallot, and Dijon; season with salt and pepper. Whisk in oil.");
  mySteps.push_back("Toss lettuces and farro with 1/3 cup dressing and divide among 4 bowls.");
  mySteps.push_back("Top with flaked trout, avocado slices, and grapefruit.");
  mySteps.push_back("Season with pepper, drizzle with more dressing, and serve.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Herbed Bean Salad";
  prepTime = 15;
  cookTime = 0;
  cuisineType = "Salad";
  myIngredients.emplace_back("3 tbsp - finely chopped", "red onion");
  myIngredients.emplace_back("2 tbsp", "red wine vinegar");
  myIngredients.emplace_back("1 3/4 cups - cooked", "cannellini beans");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("1 tsp", "Dijon mustard");
  myIngredients.emplace_back("1/4 cup", "extra-virgin olive oil");
  myIngredients.emplace_back("1/2 cup - chopped", "herbs");
  mySteps.push_back("Soak onion in cold water - 10 minutes.");
  mySteps.push_back("Meanwhile, whisk Dijon and vinegar in a bowl.");
  mySteps.push_back("Slowly whisk in oil until combined.");
  mySteps.push_back("Drain onion and dry well.");
  mySteps.push_back("Stir into dressing along with beans and herbs; season with salt and pepper.");
  mySteps.push_back("Let sit 15 to 20 minutes or refrigerate in an airtight container up to 5 days.");
  mySteps.push_back("Serve as a side, over meat and fish, on toasted rustic bread or mixed into greens.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
  title = "Pumplin Grilled Cheese";
  prepTime = 25;
  cookTime = 0;
  cuisineType = "Sandwich";
  myIngredients.emplace_back("1/4 cup", "pumpkin puree");
  myIngredients.emplace_back("to taste", "salt");
  myIngredients.emplace_back("to taste", "pepper");
  myIngredients.emplace_back("1/2 cup - grated", "white cheddar");
  myIngredients.emplace_back("1 tbsp - softened", "unsalted butter");
  myIngredients.emplace_back("1/4 tsp", "Dijon mustard");
  myIngredients.emplace_back("4 slices", "white bread");
  myIngredients.emplace_back("4 - thinly sliced", "sage leaves");
  myIngredients.emplace_back("for taste", "flaky sea salt");
  mySteps.push_back("Stir together pumpkin and mustard; season with salt and pepper.");
  mySteps.push_back("Spread 2 slices of bread with pumpkin mixture.");
  mySteps.push_back("Top with cheese and sage.");
  mySteps.push_back("Cover with remaining bread and brush both sides with butter.");
  mySteps.push_back("Cook in a large nonstick skillet over medium heat, flipping once, until golden and crisp - 8 to 10 minutes total.");
  mySteps.push_back("Serve, sprinkled with flaky salt.");
  rec = new Recipe(title, prepTime, cookTime, myIngredients, mySteps, cuisineType);
  addRecipe(rec);
  delete rec;
  myIngredients.clear();
  mySteps.clear();
  
}